### ISSUE TITLE
508 while trying to use prefill

### ISSUE THREAD

**Issue by darki73** [tpill90/battlenet-lancache-prefill#113]
**Describe the bug**
The `prefill` fails with the `508` error while attempting to prefill data.
```
[11:58:38 PM] Selected 1 apps to prefill!
[11:58:40 PM] Prefilling 1 products

[11:58:40 PM] Starting Diablo 3
[11:58:41 PM] Detected Lancache server at level3.blizzard.com [10.10.0.210]
[11:59:21 PM] Unexpected download error : Response status code does not indicate success: 508.  Skipping app...

[11:59:21 PM] Prefill complete! Prefilled 1 apps                 40.9794
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Prefilled 1 apps totaling 0 b in 43.3335

   Updated │ Up To Date │ Failed
  ━━━━━━━━━┿━━━━━━━━━━━━┿━━━━━━━━
      0    │     0      │   1

```

Issue is, the Battle.net client is able to download the files no problem, speed is way slower than downloading without the cache, but it works.

The [tpill90/battlenet-lancache-prefill](https://github.com/tpill90/battlenet-lancache-prefill) however for some reason fails to download anything while receiving the `508` error.

Even when running in docker with single ip address on the server and in the docker compose and exposing ports `80` and `443` without binding to specific addresses, it is able to detect server on the localhost, yet still produces the `508` error.

Same issue on Windows.

**Lancache Docker Compose File:**
```yaml
version: '3'

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  lancache:
    container_name: lancache
    image: lancachenet/monolithic:latest
    restart: unless-stopped
    ports:
      - 10.10.0.210:80:80/tcp
      - 10.10.0.210:443:443/tcp
      - 10.10.0.211:80:80/tcp
      - 10.10.0.211:443:443/tcp
    environment:
      USE_GENERIC_CACHE: true
      LANCACHE_IP: 10.10.0.210 10.10.0.211
      UPSTREAM_DNS: 1.1.1.1
      CACHE_DISK_SIZE: 1000g
      CACHE_INDEX_SIZE: 500m
      CACHE_MAX_AGE: 365d
      TZ: Asia/Dubai
    volumes:
      - /mnt/lancache/logs:/data/logs
      - /mnt/lancache/cache:/data/cache
      - /mnt/lancache/cachedomains:/data/cachedomains
    depends_on:
      - watchtower
```

**Pi-Hole DNSMasq configuration (/etc/dnsmasq.d/20-blizzard.conf):**
```
address=/dist.blizzard.com/10.10.0.210
local=/dist.blizzard.com/
address=/dist.blizzard.com.edgesuite.net/10.10.0.210
local=/dist.blizzard.com.edgesuite.net/
address=/blizzard.vo.llnwd.net/10.10.0.210
local=/blizzard.vo.llnwd.net/
address=/blzddist1-a.akamaihd.net/10.10.0.210
local=/blzddist1-a.akamaihd.net/
address=/blzddist2-a.akamaihd.net/10.10.0.210
local=/blzddist2-a.akamaihd.net/
address=/blzddist3-a.akamaihd.net/10.10.0.210
local=/blzddist3-a.akamaihd.net/
address=/level3.blizzard.com/10.10.0.210
local=/level3.blizzard.com/
address=/nydus.battle.net/10.10.0.210
local=/nydus.battle.net/
address=/edge.blizzard.top.comcast.net/10.10.0.210
local=/edge.blizzard.top.comcast.net/
address=/cdn.blizzard.com/10.10.0.210
local=/cdn.blizzard.com/
```

This VM is using `cloud-init` which in turn provides DNS settings for the machines as `10.10.0.200` and `10.10.0.201` (pihole1 and pihole2), but given that `prefill` should query the container itself with upstream set to `1.1.1.1`, it shouldn't be a problem.

**Comment by tpill90** [comment]
What ended up being the issue here?  Since you closed this did it end up being resolved?

**Comment by darki73** [comment]
The issue, as always, poor DNS configuration.

Here is the situation:
1. 2 Pi-Hole instances (10.10.0.200 and 10.10.0.201) in a Proxmox VM with Cloud-Init
2. Both of them using the Host settings
3. Host is using Router settings
4. Router is pointing at those 2 Pi-Hole instances
5. LOOOOOOP

But i made some changes actually down the road, now each server:
1. Has a Pi-Hole installed on the OS itself
2. Has a Docker container with Cloudflared (dns proxy for DOH)
3. Has a Lancache-DNS container pointing to a static IP of the Cloudflared container as a resolver
4. Pi-Hole points to the exposed port of the Lancache-DNS container

So it look now like: Pi-Hole (Port 53) -> Lancache-DNS Container (Port 5252) -> Cloudflared Container (Static IP + Bound to 0.0.0.0 and Port 53).

I agree, huge overhead, but at least now it works just fine:

![image](https://github.com/tpill90/battlenet-lancache-prefill/assets/1318627/37887224-54d2-45ad-94d9-459040baf54c)

**Comment by darki73** [comment]
Here is the `docker-compose.yaml` file in case someone might want to replicate this setup:
```yaml
version: '3.5'

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      custom_dns_network:
        ipv4_address: 172.25.0.2
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: proxy-dns --address 0.0.0.0 --port 53 --upstream https://1.1.1.1/dns-query --upstream https://1.0.0.1/dns-query
    networks:
      custom_dns_network:
        ipv4_address: 172.25.0.3
    depends_on:
      - watchtower
  lancache_dns:
    container_name: lancache-dns
    image: lancachenet/lancache-dns:latest
    restart: unless-stopped
    ports:
      - "5252:53/udp"
      - "5252:53/tcp"
    environment:
      # General settings
      CACHE_DOMAINS_REPO: https://github.com/uklans/cache-domains.git
      CACHE_DOMAINS_BRANCH: master
      UPSTREAM_DNS: 172.25.0.3
      TZ: Asia/Dubai
      # Lancache settings
      USE_GENERIC_CACHE: true
      LANCACHE_IP: 10.10.0.210 10.10.0.211 10.10.0.212
      # Services IPs settings
      STEAMCACHE_IP: 10.10.0.210 10.10.0.211 10.10.0.212
      BLIZZARDCACHE_IP: 10.10.0.210 10.10.0.211 10.10.0.212
      # Services settings
      DISABLE_ARENANET: true
      DISABLE_BLIZZARD: false
      DISABLE_BSG: true
      DISABLE_CITYOFHEROES: true
      DISABLE_DAYBREAK: true
      DISABLE_EPICGAMES: true
      DISABLE_FRONTIER: true
      DISABLE_NEVERWINTER: true
      DISABLE_NEXUSMODS: true
      DISABLE_NINTENDO: true
      DISABLE_ORIGIN: true
      DISABLE_PATHOFEXILE: true
      DISABLE_RENEGADEX: true
      DISABLE_RIOT: true
      DISABLE_ROCKSTAR: true
      DISABLE_SONY: true
      DISABLE_SQUARE: true
      DISABLE_STEAM: false
      DISABLE_TESO: true
      DISABLE_UPLAY: true
      DISABLE_WARFRAME: true
      DISABLE_WARGAMING: true
      DISABLE_WSUS: true
      DISABLE_XBOXLIVE: true
    networks:
      custom_dns_network:
        ipv4_address: 172.25.0.4
    depends_on:
      - cloudflared

networks:
  custom_dns_network:
    ipam:
      config:
        - subnet: 172.25.0.0/16
```

**Important:**
1. Pi-Hole is installed on the host, NOT in the docker
2. Pi-Hole is still the "main" DNS server - running on the port 53
3. In the DNS settings in the UI, you need to point Pi-Hole to `127.0.0.1#5252`
4. Change the IP addresses for the Lancache Server and if needed, the network IP and Subnet used by docker to route traffic between lancache-dns and cloudflared.
